apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garage.fullname" . }}-admin-token
  labels:
    {{- include "garage.labels" . | nindent 4 }}
type: Opaque
data:
  admin-token: {{ .Values.adminToken | b64enc | quote }}
