apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "example-02.fullname" . }}
  namespace: example-02
  labels:
    {{- include "example-02.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "example-02.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "example-02.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "example-02.fullname" . }}-env
          livenessProbe:
            httpGet:
              path: /openapi.json
              port: {{ .Values.backend.port }}
          readinessProbe:
            httpGet:
              path: /openapi.json
              port: {{ .Values.backend.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
