apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "example-02.fullname" . }}-s3
  namespace: example-02
  labels:
    {{- include "example-02.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/02-gateway-auth/s3/
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: {{ .Values.s3Service.name }}
          namespace: {{ .Values.s3Service.namespace }}
          port: {{ .Values.s3Service.port }}
    - matches:
        - path:
            type: Exact
            value: /api/login
      backendRefs:
        - name: {{ include "example-02.fullname" . }}
          namespace: example-02
          port: {{ .Values.service.port }}
