apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageBucket
metadata:
  name: alice-bucket
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "garage-instance.labels" . | nindent 4 }}
spec:
  clusterRef:
    name: {{ include "garage-instance.fullname" . }}
  quotas:
    maxSize: {{ .Values.buckets.alice.maxSize }}
