apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garage-instance.fullname" . }}-admin-token
  labels:
    {{- include "garage-instance.labels" . | nindent 4 }}
type: Opaque
data:
  admin-token: {{ .Values.adminToken | b64enc | quote }}
