gateway-helm:
  config:
    envoyGateway:
      extensionApis:
        enableEnvoyPatchPolicy: true
  deployment:
    envoyGateway:
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi

gatewayClass:
  name: eg
