apiVersion: v2
name: garage
description: Garage S3 cluster with demo buckets and backend access key (via garage-operator CRDs)
type: application
version: 0.2.0
keywords:
  - garage
  - s3
  - object-storage
home: https://garagehq.deuxfleurs.fr/
sources:
  - https://git.deuxfleurs.fr/Deuxfleurs/garage
maintainers:
  - name: tutorial-author
dependencies:
  - name: garage-operator
    # Note on upgrading: if the operator chart version is updated,
    # make sure to also update the manually copied CRDs in the crds directory.
    version: 0.0.40
    repository: oci://ghcr.io/rajsinghtech/charts
